-- +goose Up
CREATE TABLE agent_params (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    agent_id INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    params_id INTEGER NOT NULL REFERENCES params(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE agent_params;