services:

  app:
    build:
      context: app
      dockerfile: Dockerfile.dev
    ports:
    - 4200:4200
    volumes:
    - ./app/src:/app
    - /app/node_modules
    command: ["npm", "run", "docker:dev"]