services:

  app:
    build:
      context: app
      dockerfile: Dockerfile.dev
    ports:
    - 4200:4200
    volumes:
    - ./app/src:/app
    - /app/node_modules
    command: ["npm", "run", "docker:dev"]
  
  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
      args:
        - DOCKER_BUILDKIT=1
    ports:
    - 8080:8080 
    env_file:
    - .env
    depends_on:
    - db
    - migrate

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
  
  db:
    image: postgres:17.1
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME:?No postgres username provided}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?No postgres password provided}
      POSTGRES_DB: "scrapy"
  
  migrate:
    build: server/src/sql
    depends_on:
    - db
    env_file:
    - .env
    command: ["up"]